dist: bionic

language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "sxjZVZUGqfRkD3J5V+xHnCbrxrPV+ZuNkjCRfQ+Qh82s5TeJTm/HHrBuKub8xaRVRRESp1wYR+Y3/ExX57c8oTxkQWODDZ2ZZi+a50QjA/PPp2XViOfA8bWcY4wm/ME2GkBjVX/X11ZXS7jm24pY4P0GOfKgTvXyaJFBYker+mH1i8dD2RTEuNS7+rrUoKC67B94GvvikHhegKq4Z+Az6tV6E6V/IDrk4cKeWGWlsfhPrGHswnvcRpzksNlSTZV0VSHdlZBdMp3cmb064GybZgQ3O1vfrI4vdRx+qwP+4FxjFmJzsx96ssrlEX4iBS5wxlVfxjXOs4kHEcTxqS9+R3PuELOEy19+Fw48jmf06BdQRG9PgdgMX6PcT/Hssr2/iYfT/j/S3F3vAW60tK/+SJouwQBdGYFRO7iAPFKnoK9cYxtwJrCusZWrRGO7mMfzAp0X8TYX+O4jP8u4EWKpqO32pvk8q65GgBaduq5K3kLQWaYETKKvCEFtCi/dkd9tG3IoW4g4soPaokesSdo516bbpYM/SGTzwZPcBWGERLq9znaYm8UB7JDhiLYVMaA0gfAMxyv0Nh8twcki4dn6ixrv82ZGrxsiGZLLUnDQFDntwrf29iOf4Gf/wAeyAVd6V2++itU4BziUGgWRYtDtbLVwOxNR5vYbrQ0oAs5N8Yk="

before_install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - sudo apt-get install -y libefl-dev libdjvulibre-dev libtiff5-dev libarchive-dev libmupdf-dev libjbig2dec-dev e20-dev ninja-build meson python3-pip
  - pip3 install --upgrade pip
  - pip3 install --upgrade meson

script:
  - mkdir builddir && cd builddir && meson .. --buildtype=debug --default-library shared -Dlicense=agplv3 -Dmupdf-path=/usr/lib -Dmupdf-include-path=/usr/include
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ninja ; fi

addons:
  coverity_scan:
    project:
      name: "vtorri/etui"
      description: "Build submitted via Travis CI"
    notification_email: vincent.torri@gmail.com
    build_command_prepend: "mkdir builddir && cd builddir && meson .. --buildtype=debug --default-library shared -Dlicense=agplv3 -Dmupdf-path=/usr/lib -Dmupdf-include-path=/usr/include"
    build_command: "ninja"
    branch_pattern: coverity_scan
