dist: bionic
sudo: false

language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ArJhdKn10z0Ig9uWFz84xOOOnS/pyCdxVpazxoelpKxiRmueuP5hnoJNGcs/cS2faIHqndfaVQpAqCFcPSzzxCGsMMt0UC87M0eD4ZDKPfQckPD3klwDJeoJcRkvwS6rLWjMl+KQUR/sgPn20w/lkzscD6Yiu7V+JenEK5qjF6LrVgb7XpAGOCB7px0qIgM0uWk8uF0kaO8wPXI4Kt+rxRqebLOd1J8+ldc1uJshkv6uIVow6KWF5F24HS4Ky9a3/AzGrFDqa9lD3KFg8Co5xiDZiO9/XoZ/RSdJcXdewphNrhiG2kMVEeufmUSTSwH3Zc3RZ00mijw2BxFDYizQWp9jRvX8sOITMOesv39n5Og8Xrc76qEfzGUJB9Ls5gFTUL5gzMGqBE+ZlAjzqYvUoSG5kbAvdWV1u1TfWkYNg5OMJquUGLWtyob94ellvovIi+S2GDvxKU4Nush5Xb2KyHg9B1TvMGPU+RkBBZVIzTS+EHOvq6En4HQVfVHZmu44Eb5mVg5mJkwsJKnsYbPwn6kfp9yBtuNfSqBuO+OPvxnAeVSsRy3hOl6E3QeQ+bf5Z63NgGo6K9KhUD3PMTf7wCqZevoAtJcqZgEr3JWfilEC2HxR7RpFYv2r/wjs54NG6HCjpl43SCjC5GXEkIn98cEpdAfuDukEQjbzgqkBjso="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - sudo apt-get install -y libefl-dev libdjvulibre-dev libtiff5-dev libarchive-dev libopenjp2-7-dev libjbig2dec-dev ninja-build python3-pip python3-setuptools
  - pip3 install --upgrade pip
  - pip3 install meson --user

before_script:
  - wget https://mupdf.com/downloads/archive/mupdf-1.17.0-source.tar.xz -O /tmp/mupdf-1.17.0-source.tar.xz
  - tar Jxf /tmp/mupdf-1.17.0-source.tar.xz
  - cd mupdf-1.17.0-source
  - make -j prefix=/tmp/mupdf-1.17 HAVE_GLUT=no USE_SYSTEM_FREETYPE=yes USE_SYSTEM_HARFBUZZ=yes USE_SYSTEM_LIBJPEG=yes USE_SYSTEM_OPENJPEG=yes USE_SYSTEM_ZLIB=yes USE_SYSTEM_CURL=yes USE_SYSTEM_JBIG2DEC=yes SYS_JBIG2DEC_CFLAGS="-I/opt/ewpi_64/include" SYS_JBIG2DEC_LIBS="-L/opt/ewpi_64/jbig2dec/lib -ljbig2dec" SYS_FREETYPE_CFLAGS="`pkg-config --cflags freetype2`" SYS_FREETYPE_LIBS="`pkg-config --libs freetype2`" SYS_HARFBUZZ_CFLAGS="`pkg-config --cflags harfbuzz`" SYS_HARFBUZZ_LIBS="`pkg-config --libs harfbuzz`" SYS_OPENJPEG_CFLAGS="`pkg-config --cflags libopenjp2`" SYS_OPENJPEG_LIBS="`pkg-config --libs libopenjp2`" HAVE_GLFW=no XLIBS=-fPIC XCFLAGS=-fPIC
  - sudo make -j prefix=/tmp/mupdf-1.17 HAVE_GLUT=no USE_SYSTEM_FREETYPE=yes USE_SYSTEM_HARFBUZZ=yes USE_SYSTEM_LIBJPEG=yes USE_SYSTEM_OPENJPEG=yes USE_SYSTEM_ZLIB=yes USE_SYSTEM_CURL=yes USE_SYSTEM_JBIG2DEC=yes SYS_JBIG2DEC_CFLAGS="-I/opt/ewpi_64/include" SYS_JBIG2DEC_LIBS="-L/opt/ewpi_64/jbig2dec/lib -ljbig2dec" SYS_FREETYPE_CFLAGS="`pkg-config --cflags freetype2`" SYS_FREETYPE_LIBS="`pkg-config --libs freetype2`" SYS_HARFBUZZ_CFLAGS="`pkg-config --cflags harfbuzz`" SYS_HARFBUZZ_LIBS="`pkg-config --libs harfbuzz`" SYS_OPENJPEG_CFLAGS="`pkg-config --cflags libopenjp2`" SYS_OPENJPEG_LIBS="`pkg-config --libs libopenjp2`" HAVE_GLFW=no XLIBS=-fPIC XCFLAGS=-fPIC install
  - cd ..

script:
  - rm -rf builddir && mkdir builddir && cd builddir && meson .. --buildtype=debug --default-library shared -Dlicense=agplv3 -Dmupdf-libdir=/tmp/mupdf-1.17/lib -Dmupdf-includedir=/tmp/mupdf-1.17/include -Dmupdf-static-third=mupdf-third
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ninja ; fi

addons:
  coverity_scan:
    project:
      name: "vtorri/etui"
      description: "Multi-document viewer based on the EFL"
    notification_email: vincent.torri@gmail.com
    build_command_prepend: "mkdir builddir && cd builddir && meson .. --buildtype=debug --default-library shared -Dlicense=agplv3 -Dmupdf-path=/usr/lib -Dmupdf-include-path=/usr/include"
    build_command: "ninja"
    branch_pattern: coverity_scan
